#!/usr/bin/env bash
gpuId=$1
giver="kf_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JMvQ"
wallet="EQAfEzDbFCkSttDaqyu7MKCS1drGR7vPQ3nRZCRiFTkoRTUD"
dir="/home/user/ton"
miner="$dir/tonlib-cuda-cli"
[[ $2 == 'amd' ]] && miner="$dir/tonlib-opencl-cli"
miner stop
cd $dir
$miner -c global.config.json -e "pminer start $giver $wallet $gpuId"
