#!/usr/bin/env bash
gpuId=$1
giver="kf9iWhwk9GwAXjtwKG-vN7rmXT3hLIT23RBY6KhVaynRrIK7"
wallet="EQAfEzDbFCkSttDaqyu7MKCS1drGR7vPQ3nRZCRiFTkoRTUD"
dir="/home/user/ton"
miner="$dir/tonlib-cuda-cli"
[[ $2 == 'amd' ]] && miner="$dir/tonlib-opencl-cli"
miner stop
cd $dir
$miner -c global.config.json -e "pminer start $giver $wallet $gpuId"
